publisher_forward_position_controller:
  ros__parameters:

    controller_name: "forward_position_controller"
    wait_sec_between_publish: 5

    # Position for controller in sequential order

    goal_names: ["pos1", "pos2"]
    pos1: [0, 0]
    pos2: [0.01, 0.02]
